x-app-base: &app-base
  build: .
  image: lafaom_base_app
  env_file:
    - .env
  volumes:
    - .:/app


services:
  
  redis:
    image: redis:7.0.8-alpine
    networks:
      - redis_network

  celery_worker:
    <<: *app-base
    command: /start-celeryworker
    depends_on:
      - redis

  celery_beat:
    <<: *app-base
    command: /start-celerybeat
    depends_on:
      - redis
    volumes:
      - .:/app
      - celery-beat:/app/celerybeat

  app:
    <<: *app-base
    command: /start
    ports:
      - "7051:8000"
    volumes:
      - .:/app
      - app-uploads:/app/src/static/uploads
      - app-uploads-2:/app/src/uploads


volumes:
    celery-beat:
    app-uploads:
    app-uploads-2:

networks:
  
  database_network:
    name: afrolancer_backend_database_network
    external: true
  redis_network:


