# x-app-base: &app-base
#   build: .
#   image: lafaom_base_app
#   env_file:
#     - .env
#   volumes:
#     - .:/app
#   networks:
#     - database_network
#     - redis_network


# services:
  
#   redis:
#     image: redis:7.0.8-alpine
#     networks:
#       - redis_network

#   celery_worker:
#     <<: *app-base
#     command: /start-celeryworker
#     depends_on:
#       - redis

#   celery_beat:
#     <<: *app-base
#     command: /start-celerybeat
#     depends_on:
#       - redis
#     volumes:
#       - .:/app
#       - celery-beat:/app/celerybeat

#   app:
#     <<: *app-base
#     command: /start
#     ports:
#       - "7051:8000"
#     volumes:
#       - .:/app
#       - app-uploads:/app/src/static/uploads
#       - app-uploads-2:/app/src/uploads


# volumes:
#     celery-beat:
#     app-uploads:
#     app-uploads-2:

# networks:
  
#   database_network:
#     name: afrolancer_backend_database_network
#     external: true
#   redis_network:mlkl



version: "3.8"

x-app-base: &app-base
  build: .
  image: lafaom_base_app
  env_file:
    - .env
  volumes:
    - .:/app
  networks:
    - database_network
    - redis_network

services:
  db:
    image: postgres:15
    container_name: lafaom_postgres
    environment:
      POSTGRES_USER: afrolancer
      POSTGRES_PASSWORD: AZERTY
      POSTGRES_DB: lafaom_mao
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_network
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.8-alpine
    networks:
      - redis_network

  celery_worker:
    <<: *app-base
    command: /start-celeryworker
    depends_on:
      - redis
      - db

  celery_beat:
    <<: *app-base
    command: /start-celerybeat
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
      - celery-beat:/app/celerybeat

  app:
    <<: *app-base
    command: /start
    ports:
      - "7051:8000"
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
      - app-uploads:/app/src/static/uploads
      - app-uploads-2:/app/src/uploads

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lafaom_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lafaom.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - database_network
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - database_network
      - redis_network
    restart: unless-stopped

volumes:
  celery-beat:
  app-uploads:
  app-uploads-2:
  postgres_data:
  portainer_data:

networks:
  database_network:
  redis_network:
