
x-app-base: &app-base
  build: .
  image: laakam_iam_base_app
  env_file:
    - .env
  volumes:
    - .:/app
  networks:
    - redis_network

services:

  redis:
    image: redis:7.0.8-alpine
    networks:
      - redis_network
      
  celery_worker:
    <<: *app-base
    command: /start-celeryworker

  app:
    <<: *app-base
    command: /start
    ports:
      - "5050:8000"
    volumes:
      - .:/app
      - app-uploads:/app/src/static/uploads
      - app-uploads-2:/app/src/uploads

volumes:
    app-uploads:
    app-uploads-2:

networks:
  redis_network:

