
x-app-base: &app-base
  build: .
  image: laakam_iam_base_app
  env_file:
    - .env
  volumes:
    - .:/app
  networks:
    - database_network
    - redis_network

services:
  celery_worker:
    <<: *app-base
    command: /start-celeryworker

  app:
    <<: *app-base
    command: /start
    ports:
      - "5050:8000"
    volumes:
      - .:/app
      - app-uploads:/app/src/static/uploads
      - app-uploads-2:/app/src/uploads

volumes:
    app-uploads:
    app-uploads-2:

networks:
  database_network:
    name: afrolancer_backend_database_network
    external: true

  redis_network:
    name: redis_network
    external: true  
