"""organization_centers model

Revision ID: 24474a5668f8
Revises: 2e52d11c18a6
Create Date: 2025-09-19 14:56:35.282069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '24474a5668f8'
down_revision: Union[str, None] = '2e52d11c18a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_sessions', sa.Column('center_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training_sessions', 'organization_centers', ['center_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_sessions', type_='foreignkey')
    op.drop_column('training_sessions', 'center_id')
    # ### end Alembic commands ###
