"""organization_centers model

Revision ID: 2e52d11c18a6
Revises: 3d6a4f066038
Create Date: 2025-09-19 14:52:38.258092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '2e52d11c18a6'
down_revision: Union[str, None] = '3d6a4f066038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('training_sessions_center_id_fkey'), 'training_sessions', type_='foreignkey')
    op.drop_column('training_sessions', 'center_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_sessions', sa.Column('center_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('training_sessions_center_id_fkey'), 'training_sessions', 'organization_centers', ['center_id'], ['id'])
    # ### end Alembic commands ###
