"""working on training fee payment

Revision ID: 530755643e0f
Revises: 9a017ff63683
Create Date: 2025-09-22 11:22:40.644234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '530755643e0f'
down_revision: Union[str, None] = '9a017ff63683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_fee_installment_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('delete_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('User_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('training_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('rest_to_pay', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['student_applications.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('training_session_participants', sa.Column('application_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_training_session_participants_application_id'), 'training_session_participants', ['application_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_session_participants_application_id'), table_name='training_session_participants')
    op.drop_column('training_session_participants', 'application_id')
    op.drop_table('training_fee_installment_payments')
    # ### end Alembic commands ###
