"""Blog Model update

Revision ID: 5b21293586b6
Revises: 21bc9044b448
Create Date: 2025-09-10 14:58:49.461637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '5b21293586b6'
down_revision: Union[str, None] = '21bc9044b448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_categories_slug'), table_name='post_categories')
    op.create_index(op.f('ix_post_categories_slug'), 'post_categories', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_categories_slug'), table_name='post_categories')
    op.create_index(op.f('ix_post_categories_slug'), 'post_categories', ['slug'], unique=True)
    # ### end Alembic commands ###
