"""Payment Module migration

Revision ID: 656327392dbd
Revises: 8faa1ff28d9d
Create Date: 2025-09-14 18:26:53.933924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '656327392dbd'
down_revision: Union[str, None] = '8faa1ff28d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_offers', 'deadline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_offers', sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
