"""Job offers migration updated

Revision ID: 8954aa781ccc
Revises: e43c557fd4f7
Create Date: 2025-09-14 12:35:06.856912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '8954aa781ccc'
down_revision: Union[str, None] = 'e43c557fd4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'currency')
    # ### end Alembic commands ###
