"""Blog Model update add style

Revision ID: 9049924866b2
Revises: f68866562052
Create Date: 2025-09-10 17:43:54.236764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9049924866b2'
down_revision: Union[str, None] = 'f68866562052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_sections', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('post_sections', 'Content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_sections', sa.Column('Content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('post_sections', 'content')
    # ### end Alembic commands ###
