"""Specilty model

Revision ID: a3e558605267
Revises: de11a26b0a5a
Create Date: 2025-09-19 13:36:26.136956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3e558605267'
down_revision: Union[str, None] = 'de11a26b0a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_centers', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('organization_centers', sa.Column('organization_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('organization_centers', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.alter_column('reclamations', 'status',
               existing_type=postgresql.ENUM('NEW', 'IN_PROGRESS', 'CLOSED', name='reclamationstatusenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    op.drop_column('training_session_participants', 'joined_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session_participants', sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('reclamations', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=postgresql.ENUM('NEW', 'IN_PROGRESS', 'CLOSED', name='reclamationstatusenum'),
               existing_nullable=False)
    op.drop_column('organization_centers', 'description')
    op.drop_column('organization_centers', 'organization_type')
    op.drop_column('organization_centers', 'status')
    # ### end Alembic commands ###
