"""Blog Model update

Revision ID: b27b4a9eaa40
Revises: 5b21293586b6
Create Date: 2025-09-10 15:18:51.942636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b27b4a9eaa40'
down_revision: Union[str, None] = '5b21293586b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=False)
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=True)
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    # ### end Alembic commands ###
