"""Added city and country on job application

Revision ID: cb2efc7b239d
Revises: e19a9ef6ad66
Create Date: 2025-09-15 11:50:37.850843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'cb2efc7b239d'
down_revision: Union[str, None] = 'e19a9ef6ad66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('job_applications', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'address')
    op.drop_column('job_applications', 'city')
    # ### end Alembic commands ###
