"""Payment Module migration

Revision ID: e19a9ef6ad66
Revises: 656327392dbd
Create Date: 2025-09-14 18:42:24.618598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'e19a9ef6ad66'
down_revision: Union[str, None] = '656327392dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinetpay_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('delete_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_received', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('api_response_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('payment_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('payment_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cinetpay_payments_transaction_id'), 'cinetpay_payments', ['transaction_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('delete_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('product_amount', sa.Float(), nullable=False),
    sa.Column('product_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('usd_product_currency_rate', sa.Float(), nullable=False),
    sa.Column('usd_payment_currency_rate', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('payable_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payable_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_cinetpay_payments_transaction_id'), table_name='cinetpay_payments')
    op.drop_table('cinetpay_payments')
    # ### end Alembic commands ###
