"""Job offers migration updated

Revision ID: e43c557fd4f7
Revises: 37f5aa84247c
Create Date: 2025-09-14 12:03:10.386796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'e43c557fd4f7'
down_revision: Union[str, None] = '37f5aa84247c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_attachments', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_attachments', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
