"""Blog Model update add style

Revision ID: f68866562052
Revises: b27b4a9eaa40
Create Date: 2025-09-10 16:57:34.715242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'f68866562052'
down_revision: Union[str, None] = 'b27b4a9eaa40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_sections', sa.Column('section_style', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_sections', 'section_style')
    # ### end Alembic commands ###
